version: '3.1'

services:

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    volumes:
      - /home/jandson/Documents/dbdocker:/var/lib/mysql

  db:
    image: mysql:5.6
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: dbdocker
    volumes:
      - /home/jandson/Documents/dbdocker:/var/lib/mysql